name: Build

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unityVersion: [2022.3.23f1]  # Change to your Unity version
        targetPlatform: [StandaloneWindows64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true  # ⬅️ IMPORTANT for Cesium submodule

      - name: Set up cache for Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ python3

      - name: Build Cesium Native Bindings
        working-directory: Assets/Plugins/CesiumForUnity
        run: |
          chmod +x build.sh
          ./build.sh --target UnityEditor

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ./
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
